apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Apply local resource patches for minikube
patches:
  - path: opensearch-patch.yaml
  - path: monitoring-patch.yaml

